openapi: 3.0.3
info:
  title: 商南茶城 API 测试
  description: 测试接口文档
  version: 1.0.0

servers:
  - url: /api
    description: API服务

tags:
  - name: 用户模块
  - name: 茶叶模块
  - name: 店铺模块
  - name: 订单模块
  - name: 论坛模块

paths:
  # ==================== 用户模块 ====================
  /user/login:
    post:
      tags: [用户模块]
      summary: 用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 2000
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
              example:
                code: 2000
                data:
                  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

  /user/register:
    post:
      tags: [用户模块]
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 2001
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
              example:
                code: 2001
                data:
                  id: "cy100002"
                  username: "newuser"

  /user/logout:
    post:
      tags: [用户模块]
      summary: 退出登录
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 退出成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 2002
                  data:
                    nullable: true
              example:
                code: 2002
                data: null

  /user/me:
    get:
      tags: [用户模块]
      summary: 获取当前用户信息
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      nickname:
                        type: string
              example:
                code: 200
                data:
                  id: "cy100002"
                  username: "user"
                  nickname: "测试用户"

  /user/addresses:
    post:
      tags: [用户模块]
      summary: 添加收货地址
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                receiverName:
                  type: string
                receiverPhone:
                  type: string
      responses:
        '200':
          description: 添加成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 4060
                  data:
                    nullable: true
              example:
                code: 4060
                data: null

  # ==================== 茶叶模块 ====================
  /tea/list:
    get:
      tags: [茶叶模块]
      summary: 获取茶叶列表
      parameters:
        - name: page
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                      total:
                        type: integer
              example:
                code: 200
                data:
                  list:
                    - id: "tea001"
                      name: "商南绿茶"
                    - id: "tea002"
                      name: "商南红茶"
                  total: 2

  # ==================== 店铺模块 ====================
  /shop/list:
    get:
      tags: [店铺模块]
      summary: 获取店铺列表
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            logo:
                              type: string
              example:
                code: 200
                data:
                  list:
                    - id: "shop001"
                      name: "商南茶庄"
                      logo: "/images/shop1.png"
                    - id: "shop002"
                      name: "高山茶行"
                      logo: "/images/shop2.png"

  # ==================== 订单模块 ====================
  /order/create:
    post:
      tags: [订单模块]
      summary: 创建订单
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teaId:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 4000
                  data:
                    type: object
                    properties:
                      orderId:
                        type: string
                      totalPrice:
                        type: number
              example:
                code: 4000
                data:
                  orderId: "order001"
                  totalPrice: 199.00

  /order/list:
    get:
      tags: [订单模块]
      summary: 获取订单列表
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            status:
                              type: integer
              example:
                code: 200
                data:
                  list:
                    - id: "order001"
                      status: 1
                    - id: "order002"
                      status: 2

  # ==================== 论坛模块 ====================
  /forum/posts:
    post:
      tags: [论坛模块]
      summary: 发布帖子
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: 发布成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 6000
                  data:
                    type: object
                    properties:
                      postId:
                        type: string
                      title:
                        type: string
              example:
                code: 6000
                data:
                  postId: "post001"
                  title: "茶文化分享"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

